# Generated by Django 4.1.7 on 2023-05-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Event type name')),
                ('direction', models.CharField(choices=[('gpc', 'ГПЦ'), ('atn', 'АТН'), ('bel5', 'Беларусь 5')], default='bel5', help_text='The direction of Belteleradiocompany', max_length=15, verbose_name='User direction')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PlaceCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='City name')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Название Объекта')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('contact_name', models.CharField(max_length=120, verbose_name='ФИО ответственного лица на объекте')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Контактный телефон')),
                ('web', models.URLField(blank=True, verbose_name='Website Address')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('judge_system', models.CharField(blank=True, max_length=150, verbose_name='Судейская система')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Location of the broadcast',
                'verbose_name_plural': 'Broadcast locations',
                'ordering': ('name',),
            },
        ),
    ]
