# Generated by Django 2.2.16 on 2023-01-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceConstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='PTS config name')),
            ],
            options={
                'verbose_name': 'Location of the broadcast',
                'verbose_name_plural': 'Broadcast locations',
                'ordering': ('id',),
            },
        ),
    ]
