# Generated by Django 4.1.7 on 2023-05-10 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('place_broadcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeconstructor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='placeconstructor',
            name='city_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place_broadcast.placecity'),
        ),
        migrations.AddField(
            model_name='placeconstructor',
            name='event_type',
            field=models.ManyToManyField(to='place_broadcast.eventtype', verbose_name='Виды событий'),
        ),
        migrations.AddConstraint(
            model_name='placeconstructor',
            constraint=models.UniqueConstraint(fields=('name', 'city_name', 'author'), name='one_place_in_city_author'),
        ),
    ]
