# Generated by Django 2.2.16 on 2023-01-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_broadcast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeconstructor',
            name='address',
            field=models.CharField(default=1, max_length=300, verbose_name='Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeconstructor',
            name='city',
            field=models.CharField(default=1, max_length=30, verbose_name='City'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeconstructor',
            name='contact_name',
            field=models.CharField(default=1, max_length=120, verbose_name='Name of person in charge at the facility'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placeconstructor',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='placeconstructor',
            name='phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Contact phone'),
        ),
        migrations.AddField(
            model_name='placeconstructor',
            name='web',
            field=models.URLField(blank=True, verbose_name='Website Address'),
        ),
        migrations.AlterField(
            model_name='placeconstructor',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Name of the facility'),
        ),
    ]
