# Generated by Django 2.2.16 on 2023-02-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_broadcast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='City name')),
            ],
        ),
        migrations.AlterField(
            model_name='placeconstructor',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Name of the facility'),
        ),
    ]
