# Generated by Django 4.2.1 on 2023-06-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_broadcast', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeconstructor',
            name='web',
            field=models.CharField(blank=True, max_length=35, verbose_name='Website Address'),
        ),
    ]
