# Generated by Django 2.2.16 on 2023-02-09 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place_broadcast', '0002_auto_20230209_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeconstructor',
            name='city_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='place_broadcast.PlaceCity'),
            preserve_default=False,
        ),
    ]
