# Generated by Django 2.2.16 on 2023-01-13 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('place_broadcast', '0003_placeconstructor_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeconstructor',
            options={'ordering': ('create_date',), 'verbose_name': 'Location of the broadcast', 'verbose_name_plural': 'Broadcast locations'},
        ),
        migrations.AddField(
            model_name='placeconstructor',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
