# Generated by Django 2.2.16 on 2023-02-09 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place_broadcast', '0003_placeconstructor_city_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeconstructor',
            name='city',
        ),
    ]
