# Generated by Django 3.2.16 on 2023-01-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_broadcast', '0004_auto_20230113_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeconstructor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
