# Generated by Django 2.2.16 on 2023-02-14 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('place_broadcast', '0005_placecity_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeconstructor',
            name='address',
            field=models.CharField(max_length=300, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='placeconstructor',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Название Объекта'),
        ),
        migrations.AlterUniqueTogether(
            name='placecity',
            unique_together={('name', 'author')},
        ),
    ]
