# Generated by Django 2.2.16 on 2023-02-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_broadcast', '0006_auto_20230214_1818'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Event type name')),
                ('direction', models.CharField(choices=[('user', 'ГПЦ'), ('moderator', 'АТН'), ('admin', 'Беларусь 5')], default='admin', help_text='The direction of Belteleradiocompany', max_length=15, verbose_name='User direction')),
            ],
        ),
    ]
