# Generated by Django 2.2.16 on 2023-02-17 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place_broadcast', '0007_eventype'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeconstructor',
            name='even_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='place_broadcast.EvenType'),
            preserve_default=False,
        ),
    ]
