# Generated by Django 2.2.16 on 2023-02-17 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place_broadcast', '0008_placeconstructor_even_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvenType',
            new_name='EventType',
        ),
        migrations.RenameField(
            model_name='placeconstructor',
            old_name='even_type',
            new_name='event_type',
        ),
    ]
