# Generated by Django 2.2.16 on 2023-02-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_broadcast', '0009_auto_20230217_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeconstructor',
            name='event_type',
        ),
        migrations.AddField(
            model_name='placeconstructor',
            name='event_type',
            field=models.ManyToManyField(to='place_broadcast.EventType'),
        ),
    ]
