# Generated by Django 2.2.16 on 2023-02-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_broadcast', '0010_auto_20230217_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placecity',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='City name'),
        ),
        migrations.AlterUniqueTogether(
            name='placecity',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='placecity',
            name='author',
        ),
    ]
