# Generated by Django 2.2.16 on 2023-02-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_broadcast', '0011_auto_20230217_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtype',
            name='direction',
            field=models.CharField(choices=[('gpc', 'ГПЦ'), ('atn', 'АТН'), ('bel5', 'Беларусь 5')], default='bel5', help_text='The direction of Belteleradiocompany', max_length=15, verbose_name='User direction'),
        ),
    ]
