# Generated by Django 2.2.16 on 2023-02-21 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place_broadcast', '0012_auto_20230220_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeconstructor',
            name='event_type',
        ),
    ]
