# Generated by Django 4.1.7 on 2023-02-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place_broadcast', '0014_placeconstructor_event_type_alter_eventtype_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='placeconstructor',
            options={'ordering': ('name',), 'verbose_name': 'Location of the broadcast', 'verbose_name_plural': 'Broadcast locations'},
        ),
    ]
