# Generated by Django 4.1.7 on 2023-03-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_broadcast', '0015_alter_eventtype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeconstructor',
            name='contact_name',
            field=models.CharField(max_length=120, verbose_name='ФИО ответственного лица на объекте'),
        ),
        migrations.AlterField(
            model_name='placeconstructor',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='placeconstructor',
            name='event_type',
            field=models.ManyToManyField(to='place_broadcast.eventtype', verbose_name='Виды событий'),
        ),
        migrations.AlterField(
            model_name='placeconstructor',
            name='phone',
            field=models.CharField(blank=True, max_length=25, verbose_name='Контактный телефон'),
        ),
    ]
