# Generated by Django 4.1.7 on 2023-03-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_broadcast', '0016_alter_placeconstructor_contact_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='placeconstructor',
            constraint=models.UniqueConstraint(fields=('name', 'city_name', 'author'), name='one_place_in_city_author'),
        ),
    ]
