# Generated by Django 4.1.7 on 2023-03-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_broadcast', '0017_placeconstructor_one_place_in_city_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeconstructor',
            name='judge_system',
            field=models.CharField(blank=True, max_length=150, verbose_name='Судейская система'),
        ),
    ]
