# Generated by Django 2.2.16 on 2023-01-11 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('place_broadcast', '0001_initial'),
        ('pts_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadCastType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PtsName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PtsRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_date', models.DateField(blank=True, help_text='Broadcast date')),
                ('start_date', models.DateTimeField(blank=True, help_text='Broadcast start date and time')),
                ('end_date', models.DateTimeField(blank=True, help_text='Broadcast end date and time')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place_broadcast.PlaceConstructor')),
                ('pts_cfg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.PtsConstructor')),
                ('pts_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pts_requests.PtsName')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_requests.BroadCastType')),
            ],
            options={
                'verbose_name': 'PTS Request',
                'verbose_name_plural': 'PTS Requests',
                'ordering': ('broadcast_date',),
            },
        ),
    ]
