# Generated by Django 3.2.16 on 2023-01-18 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place_broadcast', '0005_alter_placeconstructor_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pts_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadCastType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PtsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PtsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_date', models.DateField(help_text='Broadcast date(YYYY-MM-DD)')),
                ('start_date', models.DateTimeField(help_text='Broadcast start date and time (YYYY-MM-DD hh:mm)')),
                ('end_date', models.DateTimeField(help_text='Broadcast end date and time (YYYY-MM-DD hh:mm)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place_broadcast.placeconstructor')),
                ('pts_cfg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.ptsconstructor', verbose_name='PTS configuration')),
                ('pts_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pts_requests.ptsname')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_requests.broadcasttype')),
            ],
            options={
                'verbose_name': 'PTS Request',
                'verbose_name_plural': 'PTS Requests',
                'ordering': ('broadcast_date',),
            },
        ),
    ]
