# Generated by Django 3.2.16 on 2023-01-19 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('place_broadcast', '0001_initial'),
        ('pts_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadCastType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PtsName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('head_fullname', models.CharField(max_length=70, verbose_name='Full name of the head of the PTS shift')),
                ('head_contact', models.CharField(max_length=100, verbose_name='Contact of the head of the PTS shift')),
                ('deputi_head_fullname', models.CharField(max_length=70, verbose_name='Full name of the deputy head of the PTS shift')),
                ('deputi_head_contact', models.CharField(max_length=100, verbose_name='Contact of the deputy head of the PTS shift')),
                ('other_informatio', models.TextField(blank=True, max_length=2000, verbose_name='Other information')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PtsRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_start_date', models.DateTimeField(help_text='Broadcast start date and time(YYYY-MM-DD hh:mm)')),
                ('broadcast_end_date', models.DateTimeField(help_text='Broadcast end date and time(YYYY-MM-DD hh:mm)')),
                ('start_date', models.DateTimeField(blank=True, help_text='Arrival date and time (YYYY-MM-DD hh:mm)')),
                ('end_date', models.DateTimeField(blank=True, help_text='Departure date and time (YYYY-MM-DD hh:mm)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place_broadcast.placeconstructor')),
                ('pts_cfg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.ptsconstructor', verbose_name='PTS configuration')),
                ('pts_name', models.ManyToManyField(blank=True, to='pts_requests.PtsName')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_requests.broadcasttype')),
            ],
            options={
                'verbose_name': 'PTS Request',
                'verbose_name_plural': 'PTS Requests',
                'ordering': ('broadcast_start_date',),
            },
        ),
    ]
