# Generated by Django 3.2.16 on 2023-01-19 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptsrequest',
            name='commentator_console',
            field=models.BooleanField(default=False, verbose_name='Sound console for commentator'),
        ),
        migrations.AddField(
            model_name='ptsrequest',
            name='commentator_headset',
            field=models.CharField(choices=[(1, 'Одна ганитура'), (2, 'Две гарнитуры')], default=1, max_length=20, verbose_name='Number of headsets'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ptsrequest',
            name='commentator_monitor',
            field=models.BooleanField(default=False, verbose_name='Monitor for commentator'),
        ),
        migrations.AddField(
            model_name='ptsrequest',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
