# Generated by Django 4.1.7 on 2023-05-11 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pts_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('place_broadcast', '0002_initial'),
        ('pts_config', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptsrequestapprovalstages',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ptsrequestapprovalstages',
            name='pts_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_requests.ptsrequest', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='ptsrequest',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ptsrequest',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place_broadcast.eventtype', verbose_name='Вид события'),
        ),
        migrations.AddField(
            model_name='ptsrequest',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='moderator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ptsrequest',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='place_broadcast.placeconstructor', verbose_name='Площадка'),
        ),
        migrations.AddField(
            model_name='ptsrequest',
            name='pts_cfg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pts_config.ptsconstructor', verbose_name='Конфигурация ПТС'),
        ),
        migrations.AddField(
            model_name='ptsrequest',
            name='pts_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pts_requests.ptsname', verbose_name='ПТС'),
        ),
        migrations.AddField(
            model_name='ptsrequest',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_requests.broadcasttype', verbose_name='Тип работы'),
        ),
        migrations.AddField(
            model_name='ptsname',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.typeptsforconfiguration'),
        ),
        migrations.AddField(
            model_name='internetlineconstructor',
            name='pts_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_requests.ptsrequest'),
        ),
        migrations.AddField(
            model_name='commlineconstructor',
            name='pts_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_requests.ptsrequest'),
        ),
    ]
