# Generated by Django 2.2.16 on 2023-01-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptsrequest',
            name='broadcast_date',
            field=models.DateField(help_text='Broadcast date'),
        ),
        migrations.AlterField(
            model_name='ptsrequest',
            name='end_date',
            field=models.DateTimeField(help_text='Broadcast end date and time'),
        ),
        migrations.AlterField(
            model_name='ptsrequest',
            name='start_date',
            field=models.DateTimeField(help_text='Broadcast start date and time'),
        ),
    ]
