# Generated by Django 2.2.16 on 2023-01-24 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='techcommlineconstructor',
            name='pts_request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pts_requests.PtsRequest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ptsrequest',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Departure date and time (YYYY-MM-DD hh:mm)', null=True),
        ),
        migrations.AlterField(
            model_name='ptsrequest',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Arrival date and time (YYYY-MM-DD hh:mm)', null=True),
        ),
    ]
