# Generated by Django 3.2.16 on 2023-01-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptsname',
            name='deputi_head_contact',
            field=models.CharField(default=1, max_length=100, verbose_name='Contact of the deputy head of the PTS shift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ptsname',
            name='deputi_head_fullname',
            field=models.CharField(default=1, max_length=70, verbose_name='Full name of the deputy head of the PTS shift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ptsname',
            name='head_contact',
            field=models.CharField(default=1, max_length=100, verbose_name='Contact of the head of the PTS shift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ptsname',
            name='head_fullname',
            field=models.CharField(default=1, max_length=70, verbose_name='Full name of the head of the PTS shift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ptsname',
            name='other_informatio',
            field=models.TextField(default=1, max_length=2000, verbose_name='Other information'),
            preserve_default=False,
        ),
    ]
