# Generated by Django 3.2.16 on 2023-01-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0002_auto_20230119_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptsrequest',
            name='commentator_headset',
            field=models.CharField(choices=[('one', 'Одна ганитура'), ('two', 'Две гарнитуры')], max_length=30, verbose_name='Number of headsets'),
        ),
    ]
