# Generated by Django 2.2.16 on 2023-01-24 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0002_auto_20230124_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptsrequest',
            name='techcommline',
        ),
    ]
