# Generated by Django 4.2.1 on 2023-06-22 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pts_requests', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptsrequest',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='director', to=settings.AUTH_USER_MODEL),
        ),
    ]
