# Generated by Django 4.2.1 on 2023-08-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0003_ptsrequest_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptsrequest',
            name='end_date_arrival',
            field=models.DateTimeField(blank=True, help_text='Дата и время прибытия ПТС на базу (YYYY-MM-DD hh:mm)', null=True, verbose_name='Дата и время прибытия ПТС на базу'),
        ),
        migrations.AddField(
            model_name='ptsrequest',
            name='start_date_arrival',
            field=models.DateTimeField(blank=True, help_text='Дата и время прибытия ПТС на объект (YYYY-MM-DD hh:mm)', null=True, verbose_name='Дата и время прибытия ПТС на объект'),
        ),
        migrations.AlterField(
            model_name='ptsrequest',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Дата и время отьезда ПТС (YYYY-MM-DD hh:mm)', null=True, verbose_name='Дата и время отьезда ПТС с объекта'),
        ),
        migrations.AlterField(
            model_name='ptsrequest',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Дата и время выезда ПТС (YYYY-MM-DD hh:mm)', null=True, verbose_name='Дата и время выезда ПТС с базы'),
        ),
    ]
