# Generated by Django 3.2.16 on 2023-01-20 13:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0003_alter_ptsrequest_commentator_headset'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechCommLineConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('to_pts', 'От ПТС к ЦА'), ('from_pts', 'От ЦА к ПТС')], max_length=20, verbose_name='Direction')),
                ('four_wire_comm', models.BooleanField(default=False, verbose_name='Four wire communication yes or no')),
                ('vpn', models.BooleanField(default=False, verbose_name='VPN communication yes or no')),
                ('pts_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_requests.ptsrequest')),
            ],
        ),
        migrations.CreateModel(
            name='CommLineConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('to_pts', 'От ПТС к ЦА'), ('from_pts', 'От ЦА к ПТС')], max_length=20, verbose_name='Direction')),
                ('internet', models.BooleanField(default=False, verbose_name='The Internet yes or no')),
                ('quantity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Quantity')),
                ('pts_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_requests.ptsrequest')),
            ],
        ),
        migrations.AddField(
            model_name='ptsrequest',
            name='commline',
            field=models.ManyToManyField(to='pts_requests.CommLineConstructor'),
        ),
        migrations.AddField(
            model_name='ptsrequest',
            name='techcommline',
            field=models.ManyToManyField(to='pts_requests.TechCommLineConstructor'),
        ),
    ]
