# Generated by Django 2.2.16 on 2023-02-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0006_ptsrequest_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ptsname',
            old_name='other_informatio',
            new_name='other_information',
        ),
        migrations.AddField(
            model_name='ptsrequest',
            name='comment',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Comment of the request'),
        ),
        migrations.AddField(
            model_name='ptsrequest',
            name='status',
            field=models.CharField(choices=[('approved', 'Утверждено'), ('rejected', 'Отклонено'), ('approval', 'На утверждении'), ('revision', 'На доработке')], default='approval', max_length=30, verbose_name='Status of the request'),
        ),
    ]
