# Generated by Django 2.2.16 on 2023-02-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0007_auto_20230207_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptsrequest',
            name='trakt_end_date',
            field=models.DateTimeField(blank=True, help_text='Trakt date and time (YYYY-MM-DD hh:mm)', null=True),
        ),
        migrations.AddField(
            model_name='ptsrequest',
            name='trakt_start_date',
            field=models.DateTimeField(blank=True, help_text='Trakt date and time (YYYY-MM-DD hh:mm)', null=True),
        ),
    ]
