# Generated by Django 2.2.16 on 2023-02-14 17:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0008_auto_20230208_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ptsrequest',
            options={'ordering': ('broadcast_start_date',), 'verbose_name': 'Заявка ПТС', 'verbose_name_plural': 'Заявка ПТС'},
        ),
        migrations.AddField(
            model_name='ptsrequest',
            name='image',
            field=models.ImageField(blank=True, upload_to='plans/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='commlineconstructor',
            name='internet',
            field=models.BooleanField(default=False, verbose_name='Предоставить Интернет на борт ПТС?'),
        ),
        migrations.AlterField(
            model_name='commlineconstructor',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='ptsname',
            name='deputi_head_contact',
            field=models.CharField(max_length=100, verbose_name='Контактный телефон  Заместителя Начальника смены ПТС'),
        ),
        migrations.AlterField(
            model_name='ptsname',
            name='deputi_head_fullname',
            field=models.CharField(max_length=70, verbose_name='ФИО Заместителя начальника смены ПТС'),
        ),
        migrations.AlterField(
            model_name='ptsname',
            name='head_contact',
            field=models.CharField(max_length=100, verbose_name='Контактный телефон  Начальника смены ПТС'),
        ),
        migrations.AlterField(
            model_name='ptsname',
            name='head_fullname',
            field=models.CharField(max_length=70, verbose_name='ФИО Начальника смены ПТС'),
        ),
        migrations.AlterField(
            model_name='ptsname',
            name='other_information',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='ptsrequest',
            name='broadcast_end_date',
            field=models.DateTimeField(help_text='Дата и время окончания трансляции(YYYY-MM-DD hh:mm)', verbose_name='Дата и время окончания трансляции'),
        ),
        migrations.AlterField(
            model_name='ptsrequest',
            name='broadcast_start_date',
            field=models.DateTimeField(help_text='Дата и время начала трансляции(YYYY-MM-DD hh:mm)', verbose_name='Дата и время начала трансляции'),
        ),
        migrations.AlterField(
            model_name='ptsrequest',
            name='comment',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Комментарий к Заявке'),
        ),
        migrations.AlterField(
            model_name='ptsrequest',
            name='commentator_console',
            field=models.BooleanField(default=False, verbose_name='Комментаторская панель'),
        ),
        migrations.AlterField(
            model_name='ptsrequest',
            name='commentator_headset',
            field=models.CharField(blank=True, choices=[('one', 'Одна ганитура'), ('two', 'Две гарнитуры')], max_length=30, null=True, verbose_name='Количество комментаторских гарнитур'),
        ),
        migrations.AlterField(
            model_name='ptsrequest',
            name='commentator_monitor',
            field=models.BooleanField(default=False, verbose_name='Комментаторский монитор'),
        ),
        migrations.AlterField(
            model_name='ptsrequest',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Дата и время отьезда ПТС (YYYY-MM-DD hh:mm)', null=True, verbose_name='Дата и время отьезда ПТС'),
        ),
        migrations.AlterField(
            model_name='ptsrequest',
            name='name',
            field=models.CharField(default='None', max_length=200, verbose_name='Название Трансляции'),
        ),
        migrations.AlterField(
            model_name='ptsrequest',
            name='pts_cfg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.PtsConstructor', verbose_name='Конфигурация ПТС'),
        ),
        migrations.AlterField(
            model_name='ptsrequest',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Дата и время выезда ПТС (YYYY-MM-DD hh:mm)', null=True, verbose_name='Дата и время выезда ПТС'),
        ),
        migrations.AlterField(
            model_name='ptsrequest',
            name='status',
            field=models.CharField(choices=[('approved', 'Утверждено'), ('rejected', 'Отклонено'), ('approval', 'На утверждении'), ('revision', 'На доработке')], default='approval', max_length=30, verbose_name='Статус Заявки'),
        ),
        migrations.AlterField(
            model_name='ptsrequest',
            name='trakt_end_date',
            field=models.DateTimeField(blank=True, help_text='Дата и время окончания тракта (YYYY-MM-DD hh:mm)', null=True, verbose_name='Дата и время окончания тракта'),
        ),
        migrations.AlterField(
            model_name='ptsrequest',
            name='trakt_start_date',
            field=models.DateTimeField(blank=True, help_text='Дата и время начала тракта (YYYY-MM-DD hh:mm)', null=True, verbose_name='Дата и время начала тракта'),
        ),
        migrations.AlterField(
            model_name='techcommlineconstructor',
            name='four_wire_comm',
            field=models.BooleanField(default=False, verbose_name='Предоставить четырехпроводный канал связи?'),
        ),
        migrations.AlterField(
            model_name='techcommlineconstructor',
            name='vpn',
            field=models.BooleanField(default=False, verbose_name='Предоставить VPN?'),
        ),
    ]
