# Generated by Django 2.2.16 on 2023-02-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0009_auto_20230214_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptsrequest',
            name='image',
            field=models.ImageField(blank=True, upload_to='plans/', verbose_name='Картинка или pdf'),
        ),
    ]
