# Generated by Django 2.2.16 on 2023-02-20 13:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0010_auto_20230217_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceInsideBT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Аппаратная')),
            ],
        ),
        migrations.RemoveField(
            model_name='commlineconstructor',
            name='internet',
        ),
        migrations.RemoveField(
            model_name='techcommlineconstructor',
            name='custom',
        ),
        migrations.RemoveField(
            model_name='techcommlineconstructor',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='techcommlineconstructor',
            name='four_wire_comm',
        ),
        migrations.RemoveField(
            model_name='techcommlineconstructor',
            name='vpn',
        ),
        migrations.AddField(
            model_name='commlineconstructor',
            name='end_date',
            field=models.DateTimeField(default='1234-01-01 01:01', help_text='Дата и время окончания трансляции(YYYY-MM-DD hh:mm)', verbose_name='Дата и время окончания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commlineconstructor',
            name='start_date',
            field=models.DateTimeField(default='1234-01-01 01:01', help_text='Дата и время начала трансляции(YYYY-MM-DD hh:mm)', verbose_name='Дата и время начала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='techcommlineconstructor',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)], verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='techcommlineconstructor',
            name='type',
            field=models.CharField(choices=[('four', 'Четырех проводка'), ('vpn', 'VPN')], default='vpn', max_length=30, verbose_name='Тип связи'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='techcommlineconstructor',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_requests.PlaceInsideBT'),
        ),
    ]
