# Generated by Django 2.2.16 on 2023-02-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0011_auto_20230220_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commlineconstructor',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='commlineconstructor',
            old_name='start_date',
            new_name='start',
        ),
    ]
