# Generated by Django 2.2.16 on 2023-02-21 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0012_auto_20230220_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptsrequest',
            name='image',
        ),
    ]
