# Generated by Django 2.2.16 on 2023-02-22 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place_broadcast', '0013_remove_placeconstructor_event_type'),
        ('pts_requests', '0013_remove_ptsrequest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptsrequest',
            name='event_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='place_broadcast.EventType'),
            preserve_default=False,
        ),
    ]
