# Generated by Django 4.1.7 on 2023-02-27 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place_broadcast', '0014_placeconstructor_event_type_alter_eventtype_id_and_more'),
        ('pts_requests', '0014_ptsrequest_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcasttype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commlineconstructor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='placeinsidebt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ptsname',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ptsrequest',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place_broadcast.eventtype', verbose_name='Вид события'),
        ),
        migrations.AlterField(
            model_name='ptsrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ptsrequest',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название Трансляции'),
        ),
        migrations.AlterField(
            model_name='ptsrequest',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place_broadcast.placeconstructor', verbose_name='Площадка'),
        ),
        migrations.AlterField(
            model_name='ptsrequest',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_requests.broadcasttype', verbose_name='Тип работы'),
        ),
        migrations.AlterField(
            model_name='techcommlineconstructor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
