# Generated by Django 4.1.7 on 2023-02-27 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0015_alter_broadcasttype_id_alter_commlineconstructor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='techcommlineconstructor',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время окончания трансляции(YYYY-MM-DD hh:mm)', verbose_name='Дата и время окончания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='techcommlineconstructor',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Дата и время начала трансляции(YYYY-MM-DD hh:mm)', verbose_name='Дата и время начала'),
            preserve_default=False,
        ),
    ]
