# Generated by Django 4.1.7 on 2023-02-27 12:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0016_techcommlineconstructor_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternetLineConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(help_text='Дата и время начала трансляции(YYYY-MM-DD hh:mm)', verbose_name='Дата и время начала')),
                ('end', models.DateTimeField(help_text='Дата и время окончания трансляции(YYYY-MM-DD hh:mm)', verbose_name='Дата и время окончания')),
                ('quantity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)], verbose_name='Количество')),
                ('speed', models.CharField(choices=[(1, '20/20 Мбит/c'), (1, '80/40 Мбит/c'), (1, '200/200 Мбит/c')], max_length=30, verbose_name='Тип связи')),
                ('pts_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_requests.ptsrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
