# Generated by Django 4.1.7 on 2023-02-27 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0017_internetlineconstructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commlineconstructor',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='internetlineconstructor',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='internetlineconstructor',
            name='speed',
            field=models.CharField(choices=[('1', '20/20 Мбит/c'), ('1', '80/40 Мбит/c'), ('1', '200/200 Мбит/c')], max_length=30, verbose_name='Скорость соединения'),
        ),
        migrations.AlterField(
            model_name='ptsrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утверждено'), ('rejected', 'Отклонено'), ('approval', 'На утверждении'), ('revision', 'На доработке')], default='draft', max_length=30, verbose_name='Статус Заявки'),
        ),
        migrations.AlterField(
            model_name='techcommlineconstructor',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)], verbose_name='Количество'),
        ),
    ]
