# Generated by Django 4.1.7 on 2023-02-28 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0009_ptsconstructor_unique_name_not_clone'),
        ('pts_requests', '0018_alter_commlineconstructor_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptsrequest',
            name='pts_cfg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pts_config.ptsconstructor', verbose_name='Конфигурация ПТС'),
        ),
    ]
