# Generated by Django 4.1.7 on 2023-03-16 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place_broadcast', '0018_placeconstructor_judge_system'),
        ('pts_requests', '0019_alter_ptsrequest_pts_cfg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptsrequest',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='place_broadcast.placeconstructor', verbose_name='Площадка'),
        ),
    ]
