# Generated by Django 4.1.7 on 2023-03-22 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0020_alter_ptsrequest_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commlineconstructor',
            name='custom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ваше направление'),
        ),
        migrations.AlterField(
            model_name='commlineconstructor',
            name='direction',
            field=models.CharField(choices=[('to_pts', 'От ЦА к ПТС'), ('from_pts', 'От ПТС к ЦА'), ('custom', 'Другое')], max_length=20, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='internetlineconstructor',
            name='speed',
            field=models.CharField(choices=[('1', '20/20 Мбит/c'), ('2', '80/40 Мбит/c'), ('3', '200/200 Мбит/c')], max_length=30, verbose_name='Скорость соединения'),
        ),
        migrations.RemoveField(
            model_name='ptsrequest',
            name='pts_name',
        ),
        migrations.AddField(
            model_name='ptsrequest',
            name='pts_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='pts_requests.ptsname', verbose_name='ПТС'),
        ),
    ]
