# Generated by Django 4.1.7 on 2023-03-23 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0020_typeptsforconfiguration_cameramodelbrend_type_and_more'),
        ('pts_requests', '0021_alter_commlineconstructor_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptsname',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.typeptsforconfiguration'),
        ),
    ]
