# Generated by Django 4.1.7 on 2023-03-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0022_ptsname_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetlineconstructor',
            name='phone',
            field=models.BooleanField(default=False, verbose_name='Наличие телефона'),
        ),
    ]
