# Generated by Django 4.1.7 on 2023-04-05 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pts_requests', '0024_ptsrequest_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptsrequest',
            name='soundman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='soundman', to=settings.AUTH_USER_MODEL),
        ),
    ]
