# Generated by Django 4.1.7 on 2023-04-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0025_ptsrequest_soundman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptsrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утверждено'), ('rejected', 'Отклонено'), ('approval', 'На утверждении'), ('soundman', 'На утверждении звукорежиссером'), ('revision', 'На доработке')], default='draft', max_length=30, verbose_name='Статус Заявки'),
        ),
    ]
