# Generated by Django 4.1.7 on 2023-04-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0026_alter_ptsrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptsrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('cancel', 'Отменена'), ('approved', 'Утверждена'), ('rejected', 'Отклонена'), ('approval', 'На утверждении'), ('soundman', 'На утверждении звукорежиссером'), ('final', 'Утверждение после звукорежиссера'), ('revision', 'На доработке')], default='draft', max_length=30, verbose_name='Статус Заявки'),
        ),
    ]
