# Generated by Django 4.1.7 on 2023-04-14 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pts_requests', '0028_alter_ptsrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptsrequest',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='ptsrequest',
            name='moderator',
        ),
        migrations.RemoveField(
            model_name='ptsrequest',
            name='soundman',
        ),
        migrations.RemoveField(
            model_name='ptsrequest',
            name='status',
        ),
        migrations.CreateModel(
            name='PtsRequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(choices=[(1, 'Черновик'), (2, 'Отклонена'), (3, 'Первичный выбор ПТС и оборудования'), (4, 'Утверждении звукорежиссером'), (5, 'Финальное подтверждение оборудования'), (6, 'Согласование ДПТР'), (7, 'Утверждена'), (0, 'Отменена')], default=3, max_length=30, verbose_name='Статус Заявки')),
                ('comment', models.TextField(blank=True, max_length=2000, verbose_name='Комментарий к согласовнию')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pts_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_requests.ptsrequest', verbose_name='Заявка')),
            ],
        ),
    ]
