# Generated by Django 4.1.7 on 2023-04-14 13:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pts_requests', '0029_remove_ptsrequest_comment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PtsRequestStatus',
            new_name='PtsRequestApprovalStages',
        ),
    ]
