# Generated by Django 4.1.7 on 2023-04-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0030_rename_ptsrequeststatus_ptsrequestapprovalstages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ptsrequestapprovalstages',
            options={'ordering': ('create_date',)},
        ),
        migrations.RenameField(
            model_name='ptsrequestapprovalstages',
            old_name='step',
            new_name='steps',
        ),
    ]
