# Generated by Django 4.1.7 on 2023-04-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0031_alter_ptsrequestapprovalstages_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptsrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('cancel', 'Отменена'), ('approved', 'Утверждена'), ('rejected', 'Отклонена'), ('approval', 'На утверждении'), ('soundman', 'На утверждении звукорежиссером'), ('final', 'Утверждение после звукорежиссера'), ('dptr', 'Согласование ДПТР')], default='draft', max_length=30, verbose_name='Статус Заявки'),
        ),
        migrations.AlterField(
            model_name='ptsrequestapprovalstages',
            name='steps',
            field=models.CharField(choices=[('1', 'Черновик'), ('2', 'Отклонена'), ('3', 'Первичный выбор ПТС и оборудования'), ('4', 'Утверждении звукорежиссером'), ('5', 'Финальное подтверждение оборудования'), ('6', 'Согласование ДПТР'), ('7', 'Утверждена'), ('0', 'Отменена')], default='3', max_length=30, verbose_name='Статус Заявки'),
        ),
    ]
