# Generated by Django 4.1.7 on 2023-04-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0032_ptsrequest_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptsrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('cancel', 'Отменена'), ('approved', 'Утверждена'), ('rejected', 'Отклонена'), ('approval', 'На утверждении'), ('soundman', 'На утверждении звукорежиссером'), ('final', 'Утверждение после звукорежиссера'), ('gdpt', 'Согласование ГДПТ'), ('dtov', 'Согласование директора ДТОВ')], default='draft', max_length=30, verbose_name='Статус Заявки'),
        ),
        migrations.AlterField(
            model_name='ptsrequestapprovalstages',
            name='steps',
            field=models.CharField(choices=[('1', 'Черновик'), ('2', 'Отклонена'), ('3', 'Отправлено на первичный выбор ПТС и оборудования'), ('4', 'Отправлено на утверждении звукорежиссером'), ('5', 'Отправлено на финальное подтверждение оборудования'), ('6', 'Отправлено на согласование ГДПТ'), ('7', 'Отправлено на согласование директору ДТОВ'), ('8', 'Утверждена'), ('0', 'Отменена')], default='3', max_length=30, verbose_name='Статус Заявки'),
        ),
    ]
