# Generated by Django 4.1.7 on 2023-05-05 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pts_requests', '0033_alter_ptsrequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptsrequest',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='moderator', to=settings.AUTH_USER_MODEL),
        ),
    ]
