# Generated by Django 2.2.16 on 2023-01-24 12:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place_broadcast', '0001_initial'),
        ('pts_config', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadCastType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PtsName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('head_fullname', models.CharField(max_length=70, verbose_name='Full name of the head of the PTS shift')),
                ('head_contact', models.CharField(max_length=100, verbose_name='Contact of the head of the PTS shift')),
                ('deputi_head_fullname', models.CharField(max_length=70, verbose_name='Full name of the deputy head of the PTS shift')),
                ('deputi_head_contact', models.CharField(max_length=100, verbose_name='Contact of the deputy head of the PTS shift')),
                ('other_informatio', models.TextField(blank=True, max_length=2000, verbose_name='Other information')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TechCommLineConstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('to_pts', 'От ЦА к ПТС'), ('from_pts', 'От ПТС к ЦА')], max_length=20, verbose_name='Direction')),
                ('four_wire_comm', models.BooleanField(default=False, verbose_name='Four wire communication yes or no')),
                ('vpn', models.BooleanField(default=False, verbose_name='VPN communication yes or no')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PtsRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_start_date', models.DateTimeField(help_text='Broadcast start date and time(YYYY-MM-DD hh:mm)')),
                ('broadcast_end_date', models.DateTimeField(help_text='Broadcast end date and time(YYYY-MM-DD hh:mm)')),
                ('start_date', models.DateTimeField(blank=True, help_text='Arrival date and time (YYYY-MM-DD hh:mm)')),
                ('end_date', models.DateTimeField(blank=True, help_text='Departure date and time (YYYY-MM-DD hh:mm)')),
                ('commentator_monitor', models.BooleanField(default=False, verbose_name='Monitor for commentator')),
                ('commentator_console', models.BooleanField(default=False, verbose_name='Sound console for commentator')),
                ('commentator_headset', models.CharField(choices=[('one', 'Одна ганитура'), ('two', 'Две гарнитуры')], max_length=30, verbose_name='Number of headsets')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place_broadcast.PlaceConstructor')),
                ('pts_cfg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.PtsConstructor', verbose_name='PTS configuration')),
                ('pts_name', models.ManyToManyField(blank=True, to='pts_requests.PtsName')),
                ('techcommline', models.ManyToManyField(related_name='techcommline', to='pts_requests.TechCommLineConstructor')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_requests.BroadCastType')),
            ],
            options={
                'verbose_name': 'PTS Request',
                'verbose_name_plural': 'PTS Requests',
                'ordering': ('broadcast_start_date',),
            },
        ),
        migrations.CreateModel(
            name='CommLineConstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('to_pts', 'От ЦА к ПТС'), ('from_pts', 'От ПТС к ЦА')], max_length=20, verbose_name='Direction')),
                ('internet', models.BooleanField(default=False, verbose_name='The Internet yes or no')),
                ('quantity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)], verbose_name='Quantity')),
                ('pts_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_requests.PtsRequest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
