# Generated by Django 2.2.16 on 2023-01-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0003_remove_ptsrequest_techcommline'),
    ]

    operations = [
        migrations.AddField(
            model_name='commlineconstructor',
            name='custom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Custom direction'),
        ),
        migrations.AddField(
            model_name='techcommlineconstructor',
            name='custom',
            field=models.CharField(blank=True, max_length=200, verbose_name='Custom direction'),
        ),
        migrations.AlterField(
            model_name='commlineconstructor',
            name='direction',
            field=models.CharField(choices=[('to_pts', 'От ЦА к ПТС'), ('from_pts', 'От ПТС к ЦА'), ('custom', 'Другое')], max_length=20, verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='techcommlineconstructor',
            name='direction',
            field=models.CharField(choices=[('to_pts', 'От ЦА к ПТС'), ('from_pts', 'От ПТС к ЦА'), ('custom', 'Другое')], max_length=20, verbose_name='Direction'),
        ),
    ]
