# Generated by Django 2.2.16 on 2023-01-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0004_auto_20230124_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptsrequest',
            name='commentator_headset',
            field=models.CharField(blank=True, choices=[('one', 'Одна ганитура'), ('two', 'Две гарнитуры')], max_length=30, null=True, verbose_name='Number of headsets'),
        ),
    ]
