# Generated by Django 2.2.16 on 2023-02-06 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_requests', '0005_auto_20230131_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptsrequest',
            name='name',
            field=models.CharField(default='None', max_length=200, verbose_name='Name of the request'),
        ),
    ]
