# Generated by Django 2.2.16 on 2023-01-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptsconstructor',
            name='cameras',
        ),
        migrations.RemoveField(
            model_name='ptsconstructor',
            name='gfxs',
        ),
        migrations.RemoveField(
            model_name='ptsconstructor',
            name='microphones',
        ),
        migrations.RemoveField(
            model_name='ptsconstructor',
            name='optics',
        ),
        migrations.RemoveField(
            model_name='ptsconstructor',
            name='servers',
        ),
        migrations.AlterField(
            model_name='ptsconstructor',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='PTS config name'),
        ),
    ]
