# Generated by Django 2.2.16 on 2023-02-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230123_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='direction',
            field=models.CharField(choices=[('user', 'ГПЦ'), ('moderator', 'АТН'), ('admin', 'Беларусь 5')], default='admin', help_text='The direction of Belteleradiocompany', max_length=15, verbose_name='User direction'),
        ),
    ]
