# Generated by Django 4.1.7 on 2023-02-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Режиссёр'), ('main_director', 'Главный режисёр'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', help_text='The rights that the user has', max_length=15, verbose_name='User role'),
        ),
    ]
