# Generated by Django 4.1.7 on 2023-03-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Режиссёр'), ('main_director', 'Главный режисёр'), ('soundman', 'Звукорежиссёр'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', help_text='The rights that the user has', max_length=15, verbose_name='User role'),
        ),
    ]
