# Generated by Django 4.1.7 on 2023-04-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='direction',
            field=models.CharField(choices=[('gpc', 'ГПЦ'), ('atn', 'АТН'), ('bel5', 'Беларусь 5'), ('dtov', 'ДТОВ'), ('gdpt', 'ГДПТ')], default='bel5', help_text='The direction of Belteleradiocompany', max_length=15, verbose_name='User direction'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Режиссёр'), ('main_director', 'Главный режисёр'), ('soundman', 'Звукорежиссёр'), ('moderator', 'Модератор'), ('admin', 'Администратор'), ('gdpt', 'ГДПТ'), ('headmaster', 'Директор ДТОВ')], default='user', help_text='The rights that the user has', max_length=15, verbose_name='User role'),
        ),
    ]
