# Generated by Django 2.2.16 on 2023-01-24 12:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Type of cameras')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CameraBrend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Camera brend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CameraModelBrend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Quantity')),
                ('name', models.CharField(max_length=50, verbose_name='Camera model')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.CameraBrend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CameraPtsConstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Quantity')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.CameraBrend')),
                ('cameras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.Camera', verbose_name='Camera type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gfx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Graphic stations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GfxLicenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='License type(kind of sport)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GfxModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Quantity')),
                ('name', models.CharField(max_length=50, verbose_name='GFX model')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.Gfx')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GfxPtsConstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Quantity')),
                ('judicial_system', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MicrophoneBrend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Type of microphones')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MicrophoneModelBrend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Quantity')),
                ('name', models.CharField(max_length=50, verbose_name='Microphone model')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.MicrophoneBrend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MicrophonePtsConstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Quantity')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.MicrophoneBrend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MicrophoneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Type of microphones')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Optic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Optical magnification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpticBrend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Optic brend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpticModelBrend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Quantity')),
                ('name', models.CharField(max_length=50, verbose_name='Optic model')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.OpticBrend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpticPtsConstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Quantity')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.OpticBrend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PtsConstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='PTS config name')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cameras', models.ManyToManyField(blank=True, through='pts_config.CameraPtsConstructor', to='pts_config.Camera')),
                ('gfxs', models.ManyToManyField(blank=True, through='pts_config.GfxPtsConstructor', to='pts_config.Gfx')),
                ('microphones', models.ManyToManyField(blank=True, through='pts_config.MicrophonePtsConstructor', to='pts_config.MicrophoneType')),
                ('optics', models.ManyToManyField(blank=True, through='pts_config.OpticPtsConstructor', to='pts_config.Optic')),
            ],
            options={
                'verbose_name': 'PTS config',
                'verbose_name_plural': 'PTS configs',
                'ordering': ('create_date',),
            },
        ),
        migrations.CreateModel(
            name='ServerPlayerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Server player type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServerRecordingRepeatBrend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Server brend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServerRecordingRepeatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Server type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServerRecordingRepeatModelBrend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Quantity')),
                ('name', models.CharField(max_length=50, verbose_name='Server model')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.ServerRecordingRepeatBrend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServerRecordingRepeatConstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Quantity')),
                ('brend', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.ServerRecordingRepeatBrend')),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.PtsConstructor')),
                ('model', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.ServerRecordingRepeatModelBrend')),
                ('type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.ServerRecordingRepeatType')),
                ('type_player', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.ServerPlayerType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ptsconstructor',
            name='servers',
            field=models.ManyToManyField(blank=True, through='pts_config.ServerRecordingRepeatConstructor', to='pts_config.ServerRecordingRepeatType'),
        ),
        migrations.AddField(
            model_name='opticptsconstructor',
            name='constructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.PtsConstructor'),
        ),
        migrations.AddField(
            model_name='opticptsconstructor',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.OpticModelBrend'),
        ),
        migrations.AddField(
            model_name='opticptsconstructor',
            name='optics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.Optic', verbose_name='Optical magnification'),
        ),
        migrations.AddField(
            model_name='microphoneptsconstructor',
            name='constructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.PtsConstructor'),
        ),
        migrations.AddField(
            model_name='microphoneptsconstructor',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.MicrophoneModelBrend'),
        ),
        migrations.AddField(
            model_name='microphoneptsconstructor',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.MicrophoneType'),
        ),
        migrations.AddField(
            model_name='gfxptsconstructor',
            name='constructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.PtsConstructor'),
        ),
        migrations.AddField(
            model_name='gfxptsconstructor',
            name='gfx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gfx', to='pts_config.Gfx'),
        ),
        migrations.AddField(
            model_name='gfxptsconstructor',
            name='license_type',
            field=models.ManyToManyField(blank=True, to='pts_config.GfxLicenseType'),
        ),
        migrations.AddField(
            model_name='gfxptsconstructor',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.GfxModel'),
        ),
        migrations.AddField(
            model_name='cameraptsconstructor',
            name='constructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.PtsConstructor'),
        ),
        migrations.AddField(
            model_name='cameraptsconstructor',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.CameraModelBrend'),
        ),
    ]
