# Generated by Django 3.2.16 on 2023-01-19 17:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Type of cameras')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CameraBrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Camera brend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CameraModelBrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Camera model')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.camerabrend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CameraPtsConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Quantity')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.camerabrend')),
                ('cameras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.camera', verbose_name='Camera type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gfx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Graphic stations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GfxLicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='License type(kind of sport)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GfxModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='GFX model')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.gfx')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GfxPtsConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Quantity')),
                ('judicial_system', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MicrophoneBrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Type of microphones')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MicrophoneModelBrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Microphone model')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.microphonebrend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MicrophonePtsConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Quantity')),
                ('type', models.CharField(choices=[('gun', 'Пушка'), ('half_gun', 'Полупушка'), ('hand_stereo', 'Ручной стерео')], max_length=20, verbose_name='Micro type')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.microphonebrend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Optic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Optical magnification')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpticBrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Optic brend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpticModelBrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Optic model')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.opticbrend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpticPtsConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Quantity')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.opticbrend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PtsConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='PTS config name')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cameras', models.ManyToManyField(blank=True, through='pts_config.CameraPtsConstructor', to='pts_config.Camera')),
                ('gfxs', models.ManyToManyField(blank=True, through='pts_config.GfxPtsConstructor', to='pts_config.Gfx')),
                ('microphones', models.ManyToManyField(to='pts_config.MicrophonePtsConstructor')),
                ('optics', models.ManyToManyField(blank=True, through='pts_config.OpticPtsConstructor', to='pts_config.Optic')),
            ],
            options={
                'verbose_name': 'PTS config',
                'verbose_name_plural': 'PTS configs',
                'ordering': ('create_date',),
            },
        ),
        migrations.CreateModel(
            name='ServerPlayerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Server player type')),
                ('type', models.CharField(choices=[('recording', 'Сервер записи'), ('repeat', 'Сервер повтора')], max_length=20, verbose_name='Server type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServerRecordingRepeatBrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Server brend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServerRecordingRepeatModelBrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Server model')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.serverrecordingrepeatbrend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServerRecordingRepeatConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Quantity')),
                ('type', models.CharField(blank=True, choices=[('recording', 'Сервер записи'), ('repeat', 'Сервер повтора')], default=None, max_length=20, verbose_name='Server type')),
                ('brend', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.serverrecordingrepeatbrend')),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.ptsconstructor')),
                ('model', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.serverrecordingrepeatmodelbrend')),
                ('type_player', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.serverplayertype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ptsconstructor',
            name='servers',
            field=models.ManyToManyField(to='pts_config.ServerRecordingRepeatConstructor'),
        ),
        migrations.AddField(
            model_name='opticptsconstructor',
            name='constructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.ptsconstructor'),
        ),
        migrations.AddField(
            model_name='opticptsconstructor',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.opticmodelbrend'),
        ),
        migrations.AddField(
            model_name='opticptsconstructor',
            name='optics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.optic', verbose_name='Optical magnification'),
        ),
        migrations.AddField(
            model_name='microphoneptsconstructor',
            name='constructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.ptsconstructor'),
        ),
        migrations.AddField(
            model_name='microphoneptsconstructor',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.microphonemodelbrend'),
        ),
        migrations.AddField(
            model_name='gfxptsconstructor',
            name='constructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.ptsconstructor'),
        ),
        migrations.AddField(
            model_name='gfxptsconstructor',
            name='gfx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gfx', to='pts_config.gfx'),
        ),
        migrations.AddField(
            model_name='gfxptsconstructor',
            name='license_type',
            field=models.ManyToManyField(blank=True, to='pts_config.GfxLicenseType'),
        ),
        migrations.AddField(
            model_name='gfxptsconstructor',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.gfxmodel'),
        ),
        migrations.AddField(
            model_name='cameraptsconstructor',
            name='constructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.ptsconstructor'),
        ),
        migrations.AddField(
            model_name='cameraptsconstructor',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.cameramodelbrend'),
        ),
    ]
