# Generated by Django 4.1.7 on 2023-05-10 15:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Type of cameras')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CameraBrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Camera brend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CameraModelBrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Quantity')),
                ('name', models.CharField(max_length=50, verbose_name='Camera model')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CameraPtsConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Количество')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gfx',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Graphic stations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GfxLicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='License type(kind of sport)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GfxModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Quantity')),
                ('name', models.CharField(max_length=50, verbose_name='GFX model')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GfxPtsConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judicial_system', models.BooleanField(default=False, verbose_name='Подключение к судейской системе?')),
                ('quantity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Количество')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MicrophoneBrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Type of microphones')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MicrophoneModelBrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Quantity')),
                ('name', models.CharField(max_length=50, verbose_name='Microphone model')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MicrophonePtsConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Количество')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MicrophoneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Type of microphones')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Optic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Optical magnification')),
                ('visible_to_user', models.BooleanField(default=False, verbose_name='Видят ли пользователи')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpticBrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Optic brend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpticModelBrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Quantity')),
                ('name', models.CharField(max_length=50, verbose_name='Optic model')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OpticPtsConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Количество')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PtsConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название конфигурации ПТС')),
                ('base_conf', models.BooleanField(default=False, verbose_name='Базовая комплектация')),
                ('clone_conf', models.BooleanField(default=False, verbose_name='Комплектация привязаная к заявке')),
                ('microphone_quantity', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Количество')),
                ('image', models.ImageField(blank=True, upload_to='plans/', verbose_name='Картинка или pdf')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Конфигурация ПТС',
                'verbose_name_plural': 'PTS configs',
                'ordering': ('create_date',),
            },
        ),
        migrations.CreateModel(
            name='ServerPlayerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Server player type')),
                ('visible_to_user', models.BooleanField(default=False, verbose_name='Видят ли пользователи')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServerRecordingRepeatBrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Server brend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServerRecordingRepeatType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Server type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypePtsForConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Type of PTS')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServerRecordingRepeatModelBrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Quantity')),
                ('name', models.CharField(max_length=50, verbose_name='Server model')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.serverrecordingrepeatbrend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServerRecordingRepeatConstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Количество')),
                ('brend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.serverrecordingrepeatbrend')),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.ptsconstructor')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.serverrecordingrepeatmodelbrend')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.serverrecordingrepeattype')),
                ('type_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.serverplayertype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='serverrecordingrepeatbrend',
            name='type_pts',
            field=models.ForeignKey(blank=True, help_text='If this brand can be used everywhere, choose nothing', null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.typeptsforconfiguration'),
        ),
        migrations.AddField(
            model_name='serverplayertype',
            name='rec_rep_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.serverrecordingrepeattype'),
        ),
    ]
