# Generated by Django 4.1.7 on 2023-05-10 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('place_broadcast', '0002_initial'),
        ('pts_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptsconstructor',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ptsconstructor',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place_broadcast.eventtype'),
        ),
        migrations.AddField(
            model_name='ptsconstructor',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place_broadcast.placeconstructor'),
        ),
        migrations.AddField(
            model_name='opticptsconstructor',
            name='brend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.opticbrend'),
        ),
        migrations.AddField(
            model_name='opticptsconstructor',
            name='constructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.ptsconstructor'),
        ),
        migrations.AddField(
            model_name='opticptsconstructor',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.opticmodelbrend'),
        ),
        migrations.AddField(
            model_name='opticptsconstructor',
            name='optics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.optic', verbose_name='Кратность Оптики'),
        ),
        migrations.AddField(
            model_name='opticmodelbrend',
            name='brend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.opticbrend'),
        ),
        migrations.AddField(
            model_name='opticmodelbrend',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.optic'),
        ),
        migrations.AddField(
            model_name='opticbrend',
            name='type_pts',
            field=models.ForeignKey(blank=True, help_text='If this brand can be used everywhere, choose nothing', null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.typeptsforconfiguration'),
        ),
        migrations.AddField(
            model_name='microphoneptsconstructor',
            name='brend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.microphonebrend'),
        ),
        migrations.AddField(
            model_name='microphoneptsconstructor',
            name='constructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.ptsconstructor'),
        ),
        migrations.AddField(
            model_name='microphoneptsconstructor',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.microphonemodelbrend'),
        ),
        migrations.AddField(
            model_name='microphoneptsconstructor',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.microphonetype'),
        ),
        migrations.AddField(
            model_name='microphonemodelbrend',
            name='brend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.microphonebrend'),
        ),
        migrations.AddField(
            model_name='microphonemodelbrend',
            name='type_micro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.microphonetype'),
        ),
        migrations.AddField(
            model_name='microphonemodelbrend',
            name='type_pts',
            field=models.ForeignKey(blank=True, help_text='If this brand can be used everywhere, choose nothing', null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.typeptsforconfiguration'),
        ),
        migrations.AddField(
            model_name='gfxptsconstructor',
            name='constructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.ptsconstructor'),
        ),
        migrations.AddField(
            model_name='gfxptsconstructor',
            name='gfx',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gfx', to='pts_config.gfx'),
        ),
        migrations.AddField(
            model_name='gfxptsconstructor',
            name='license_type',
            field=models.ManyToManyField(blank=True, to='pts_config.gfxlicensetype'),
        ),
        migrations.AddField(
            model_name='gfxptsconstructor',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.gfxmodel'),
        ),
        migrations.AddField(
            model_name='gfxmodel',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.gfx'),
        ),
        migrations.AddField(
            model_name='cameraptsconstructor',
            name='brend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.camerabrend', verbose_name='Производитель камеры'),
        ),
        migrations.AddField(
            model_name='cameraptsconstructor',
            name='cameras',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.camera', verbose_name='Тип Камеры'),
        ),
        migrations.AddField(
            model_name='cameraptsconstructor',
            name='constructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.ptsconstructor'),
        ),
        migrations.AddField(
            model_name='cameraptsconstructor',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.cameramodelbrend'),
        ),
        migrations.AddField(
            model_name='cameramodelbrend',
            name='brend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.camerabrend'),
        ),
        migrations.AddField(
            model_name='cameramodelbrend',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.camera'),
        ),
        migrations.AddField(
            model_name='camerabrend',
            name='type_pts',
            field=models.ForeignKey(blank=True, help_text='If this brand can be used everywhere, choose nothing', null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.typeptsforconfiguration'),
        ),
        migrations.AddConstraint(
            model_name='ptsconstructor',
            constraint=models.UniqueConstraint(condition=models.Q(('base_conf', False), ('clone_conf', False)), fields=('name', 'author'), name='unique_name_for_not_clone'),
        ),
        migrations.AddConstraint(
            model_name='ptsconstructor',
            constraint=models.UniqueConstraint(condition=models.Q(('base_conf', True)), fields=('event_type', 'place', 'author'), name='one_base_cfg_to_event_place_author'),
        ),
    ]
