# Generated by Django 3.2.16 on 2023-01-18 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpticBrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Type of cameras')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='cameraptsconstructor',
            name='cameras',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.camera', verbose_name='Camera type'),
        ),
        migrations.AlterField(
            model_name='optic',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Type of cameras'),
        ),
        migrations.CreateModel(
            name='OpticModelBrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Type of cameras')),
                ('brend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.opticbrend')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='opticptsconstructor',
            name='brend',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='pts_config.opticbrend'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opticptsconstructor',
            name='model',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='pts_config.opticmodelbrend'),
            preserve_default=False,
        ),
    ]
