# Generated by Django 3.2.16 on 2023-01-18 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverrecordingrepeatconstructor',
            name='brend',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.serverrecordingrepeatbrend'),
        ),
        migrations.AlterField(
            model_name='serverrecordingrepeatconstructor',
            name='model',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.serverrecordingrepeatmodelbrend'),
        ),
    ]
