# Generated by Django 2.2.16 on 2023-01-11 17:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Type of cameras')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commentator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Type of commentary equipment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gfx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Graphic stations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Microphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Type of microphones')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Optic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Type of optics')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='ptsconstructor',
            options={'ordering': ('name',), 'verbose_name': 'PTS config', 'verbose_name_plural': 'PTS configs'},
        ),
        migrations.CreateModel(
            name='OpticPtsConstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Quantity')),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.PtsConstructor')),
                ('optics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.Optic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MicrophonePtsConstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Quantity')),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.PtsConstructor')),
                ('microphones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.Microphone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GfxPtsConstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Quantity')),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.PtsConstructor')),
                ('gfx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gfx', to='pts_config.Gfx')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentatorPtsConstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Quantity')),
                ('commentators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.Commentator')),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.PtsConstructor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CameraPtsConstructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Quantity')),
                ('cameras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.Camera')),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.PtsConstructor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ptsconstructor',
            name='cameras',
            field=models.ManyToManyField(through='pts_config.CameraPtsConstructor', to='pts_config.Camera'),
        ),
        migrations.AddField(
            model_name='ptsconstructor',
            name='commentators',
            field=models.ManyToManyField(through='pts_config.CommentatorPtsConstructor', to='pts_config.Commentator'),
        ),
        migrations.AddField(
            model_name='ptsconstructor',
            name='gfxs',
            field=models.ManyToManyField(through='pts_config.GfxPtsConstructor', to='pts_config.Gfx'),
        ),
        migrations.AddField(
            model_name='ptsconstructor',
            name='microphones',
            field=models.ManyToManyField(through='pts_config.MicrophonePtsConstructor', to='pts_config.Microphone'),
        ),
        migrations.AddField(
            model_name='ptsconstructor',
            name='optics',
            field=models.ManyToManyField(through='pts_config.OpticPtsConstructor', to='pts_config.Optic'),
        ),
    ]
