# Generated by Django 2.2.16 on 2023-02-14 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0002_auto_20230124_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ptsconstructor',
            options={'ordering': ('create_date',), 'verbose_name': 'Конфигурация ПТС', 'verbose_name_plural': 'PTS configs'},
        ),
        migrations.AlterField(
            model_name='cameraptsconstructor',
            name='brend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.CameraBrend', verbose_name='Производитель камеры'),
        ),
        migrations.AlterField(
            model_name='cameraptsconstructor',
            name='cameras',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.Camera', verbose_name='Тип Камеры'),
        ),
        migrations.AlterField(
            model_name='gfxptsconstructor',
            name='judicial_system',
            field=models.BooleanField(default=False, verbose_name='Подключение к судейской системе?'),
        ),
        migrations.AlterField(
            model_name='opticptsconstructor',
            name='optics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.Optic', verbose_name='Кратность Оптики'),
        ),
        migrations.AlterField(
            model_name='ptsconstructor',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название конфигурации ПТС'),
        ),
    ]
