# Generated by Django 4.2.1 on 2023-05-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptsconstructor',
            name='microphone_comment',
            field=models.TextField(blank=True, max_length=2000, verbose_name='Комментарий к заказу микрофонов'),
        ),
    ]
