# Generated by Django 3.2.16 on 2023-01-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0002_auto_20230118_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='GfxLicenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='License type(kind of sport)')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='camerabrend',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Camera brend'),
        ),
        migrations.AlterField(
            model_name='cameramodelbrend',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Camera model'),
        ),
        migrations.AlterField(
            model_name='gfx',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Graphic stations'),
        ),
        migrations.AlterField(
            model_name='gfxmodel',
            name='name',
            field=models.CharField(max_length=20, verbose_name='GFX model'),
        ),
        migrations.AlterField(
            model_name='microphonebrend',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Type of microphones'),
        ),
        migrations.AlterField(
            model_name='microphonemodelbrend',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Microphone model'),
        ),
        migrations.AlterField(
            model_name='optic',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Optical magnification'),
        ),
        migrations.AlterField(
            model_name='opticbrend',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Optic brend'),
        ),
        migrations.AlterField(
            model_name='opticmodelbrend',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Optic model'),
        ),
        migrations.AlterField(
            model_name='serverrecordingrepeatbrend',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Server brend'),
        ),
        migrations.AlterField(
            model_name='serverrecordingrepeatmodelbrend',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Server model'),
        ),
        migrations.AddField(
            model_name='gfxptsconstructor',
            name='license_type',
            field=models.ManyToManyField(blank=True, to='pts_config.GfxLicenseType'),
        ),
    ]
