# Generated by Django 2.2.16 on 2023-02-20 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place_broadcast', '0012_auto_20230220_1118'),
        ('pts_config', '0003_auto_20230214_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptsconstructor',
            name='event_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='place_broadcast.EventType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ptsconstructor',
            name='place',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='place_broadcast.PlaceConstructor'),
            preserve_default=False,
        ),
    ]
