# Generated by Django 4.2.1 on 2023-06-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0003_ptsconstructor_microphone_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptsconstructor',
            name='microphone_comment',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Комментарий к заказу микрофонов'),
        ),
    ]
