# Generated by Django 4.2.1 on 2023-07-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0004_alter_ptsconstructor_microphone_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptsconstructor',
            name='commentator_comment',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Комментарий к заказу микрофонов'),
        ),
        migrations.AddField(
            model_name='ptsconstructor',
            name='commentator_headsets',
            field=models.BooleanField(default=False, verbose_name='Комментаторские гарнитуры'),
        ),
        migrations.AddField(
            model_name='ptsconstructor',
            name='commentator_position',
            field=models.BooleanField(default=False, verbose_name='Комментаторская позиция'),
        ),
    ]
