# Generated by Django 2.2.16 on 2023-02-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0004_auto_20230220_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptsconstructor',
            name='base_conf',
            field=models.BooleanField(default=False, verbose_name='Базовая комплектация'),
        ),
    ]
