# Generated by Django 4.2.1 on 2023-08-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0005_ptsconstructor_commentator_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptsconstructor',
            name='commentator_comment',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Комментарий к заказу оборудования для комментаторской позиции'),
        ),
    ]
