# Generated by Django 4.2.1 on 2023-08-17 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0006_alter_ptsconstructor_commentator_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_data', models.BinaryField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ptsconstructor',
            name='image_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.imagebank'),
        ),
    ]
