# Generated by Django 4.1.7 on 2023-02-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0006_alter_camera_id_alter_camerabrend_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptsconstructor',
            name='clone_conf',
            field=models.BooleanField(default=False, verbose_name='Комплектация привязаная к заявке'),
        ),
    ]
