# Generated by Django 4.2.1 on 2023-08-17 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0007_imagebank_ptsconstructor_image_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptsconstructor',
            name='image_bank',
        ),
        migrations.AddField(
            model_name='imagebank',
            name='pts_cfg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.ptsconstructor'),
        ),
    ]
