# Generated by Django 4.1.7 on 2023-02-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0007_ptsconstructor_clone_conf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptsconstructor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название конфигурации ПТС'),
        ),
    ]
