# Generated by Django 4.1.7 on 2023-02-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0008_alter_ptsconstructor_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ptsconstructor',
            constraint=models.UniqueConstraint(condition=models.Q(('clone_conf', False)), fields=('name',), name='unique_name_not_clone'),
        ),
    ]
