# Generated by Django 4.1.7 on 2023-03-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0009_ptsconstructor_unique_name_not_clone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptsconstructor',
            name='image',
            field=models.ImageField(blank=True, upload_to='plans/', verbose_name='Картинка или pdf'),
        ),
    ]
