# Generated by Django 4.1.7 on 2023-03-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0010_ptsconstructor_image'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ptsconstructor',
            name='unique_name_not_clone',
        ),
        migrations.AddConstraint(
            model_name='ptsconstructor',
            constraint=models.UniqueConstraint(condition=models.Q(('clone_conf', False)), fields=('name',), name='unique_name_for_not_clone'),
        ),
        migrations.AddConstraint(
            model_name='ptsconstructor',
            constraint=models.UniqueConstraint(condition=models.Q(('base_conf', True)), fields=('event_type', 'place', 'author'), name='one_base_cfg_to_event_place_author'),
        ),
    ]
