# Generated by Django 4.1.7 on 2023-03-03 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0011_remove_ptsconstructor_unique_name_not_clone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptsconstructor',
            name='microphone_quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Quantity'),
        ),
    ]
