# Generated by Django 4.1.7 on 2023-03-03 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0012_ptsconstructor_microphone_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraptsconstructor',
            name='brend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.camerabrend', verbose_name='Производитель камеры'),
        ),
        migrations.AlterField(
            model_name='cameraptsconstructor',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.cameramodelbrend'),
        ),
        migrations.AlterField(
            model_name='opticptsconstructor',
            name='brend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.opticbrend'),
        ),
        migrations.AlterField(
            model_name='opticptsconstructor',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.opticmodelbrend'),
        ),
        migrations.AlterField(
            model_name='serverrecordingrepeatconstructor',
            name='brend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.serverrecordingrepeatbrend'),
        ),
        migrations.AlterField(
            model_name='serverrecordingrepeatconstructor',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.serverrecordingrepeatmodelbrend'),
        ),
    ]
