# Generated by Django 4.1.7 on 2023-03-06 09:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0013_alter_cameraptsconstructor_brend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraptsconstructor',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='gfxptsconstructor',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.gfxmodel'),
        ),
        migrations.AlterField(
            model_name='gfxptsconstructor',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='microphoneptsconstructor',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='opticptsconstructor',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='serverrecordingrepeatconstructor',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Количество'),
        ),
    ]
