# Generated by Django 4.1.7 on 2023-03-06 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0014_alter_cameraptsconstructor_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverrecordingrepeatconstructor',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.serverrecordingrepeattype'),
        ),
        migrations.AlterField(
            model_name='serverrecordingrepeatconstructor',
            name='type_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pts_config.serverplayertype'),
        ),
    ]
