# Generated by Django 4.1.7 on 2023-03-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0016_remove_ptsconstructor_unique_name_for_not_clone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opticptsconstructor',
            name='visible_to_user',
            field=models.BooleanField(default=False, verbose_name='Видят ли пользователи'),
        ),
    ]
