# Generated by Django 4.1.7 on 2023-03-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0017_opticptsconstructor_visible_to_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opticptsconstructor',
            name='visible_to_user',
        ),
    ]
