# Generated by Django 4.1.7 on 2023-03-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0018_remove_opticptsconstructor_visible_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='optic',
            name='visible_to_user',
            field=models.BooleanField(default=False, verbose_name='Видят ли пользователи'),
        ),
    ]
