# Generated by Django 4.1.7 on 2023-03-23 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0019_optic_visible_to_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypePtsForConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Type of PTS')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cameramodelbrend',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.camera'),
        ),
        migrations.AddField(
            model_name='camerabrend',
            name='type_pts',
            field=models.ForeignKey(blank=True, help_text='If this brand can be used everywhere, choose nothing', null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.typeptsforconfiguration'),
        ),
    ]
