# Generated by Django 4.1.7 on 2023-03-27 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0020_typeptsforconfiguration_cameramodelbrend_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opticbrend',
            name='type_pts',
            field=models.ForeignKey(blank=True, help_text='If this brand can be used everywhere, choose nothing', null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.typeptsforconfiguration'),
        ),
        migrations.AddField(
            model_name='opticmodelbrend',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.optic'),
        ),
    ]
