# Generated by Django 4.1.7 on 2023-03-28 14:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0021_opticbrend_type_pts_opticmodelbrend_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverplayertype',
            name='rec_rep_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pts_config.serverrecordingrepeattype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cameraptsconstructor',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='gfxptsconstructor',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='microphoneptsconstructor',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='opticptsconstructor',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='serverrecordingrepeatconstructor',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Количество'),
        ),
    ]
