# Generated by Django 4.1.7 on 2023-03-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0022_serverplayertype_rec_rep_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverplayertype',
            name='visible_to_user',
            field=models.BooleanField(default=False, verbose_name='Видят ли пользователи'),
        ),
    ]
