# Generated by Django 4.1.7 on 2023-03-29 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0024_serverrecordingrepeatbrend_type_pts'),
    ]

    operations = [
        migrations.AddField(
            model_name='microphonemodelbrend',
            name='type_pts',
            field=models.ForeignKey(blank=True, help_text='If this brand can be used everywhere, choose nothing', null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.typeptsforconfiguration'),
        ),
    ]
