# Generated by Django 4.1.7 on 2023-03-29 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0025_microphonemodelbrend_type_pts'),
    ]

    operations = [
        migrations.AddField(
            model_name='microphonemodelbrend',
            name='type_micro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pts_config.microphonetype'),
            preserve_default=False,
        ),
    ]
