# Generated by Django 4.1.7 on 2023-03-30 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0026_microphonemodelbrend_type_micro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microphoneptsconstructor',
            name='brend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.microphonebrend'),
        ),
        migrations.AlterField(
            model_name='microphoneptsconstructor',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pts_config.microphonemodelbrend'),
        ),
    ]
