# Generated by Django 4.1.7 on 2023-04-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0027_alter_microphoneptsconstructor_brend_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ptsconstructor',
            name='unique_name_for_not_clone',
        ),
        migrations.AddConstraint(
            model_name='ptsconstructor',
            constraint=models.UniqueConstraint(condition=models.Q(('base_conf', False), ('clone_conf', False)), fields=('name', 'author'), name='unique_name_for_not_clone'),
        ),
    ]
