# Generated by Django 4.1.7 on 2023-05-10 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pts_config', '0028_remove_ptsconstructor_unique_name_for_not_clone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gfxmodel',
            name='quantity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Quantity'),
        ),
    ]
